// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHxxa7gR00Xz493u_-5UV_E4aW0O4-oc',
    appId: '1:120615867415:web:7774aeda1e348de1307852',
    messagingSenderId: '120615867415',
    projectId: 'responsive-design-cac6f',
    authDomain: 'responsive-design-cac6f.firebaseapp.com',
    storageBucket: 'responsive-design-cac6f.firebasestorage.app',
    measurementId: 'G-GX32CH12YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNn-dcxWPW6CmHYwkkq1LrI0B_iNoCQpo',
    appId: '1:120615867415:android:286533fded9031bd307852',
    messagingSenderId: '120615867415',
    projectId: 'responsive-design-cac6f',
    storageBucket: 'responsive-design-cac6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5KuiVF4qqEdCQ4mvzhF9Eo1EaJWccxSY',
    appId: '1:120615867415:ios:95facb8db1d18632307852',
    messagingSenderId: '120615867415',
    projectId: 'responsive-design-cac6f',
    storageBucket: 'responsive-design-cac6f.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5KuiVF4qqEdCQ4mvzhF9Eo1EaJWccxSY',
    appId: '1:120615867415:ios:95facb8db1d18632307852',
    messagingSenderId: '120615867415',
    projectId: 'responsive-design-cac6f',
    storageBucket: 'responsive-design-cac6f.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHxxa7gR00Xz493u_-5UV_E4aW0O4-oc',
    appId: '1:120615867415:web:f1147cd99281f025307852',
    messagingSenderId: '120615867415',
    projectId: 'responsive-design-cac6f',
    authDomain: 'responsive-design-cac6f.firebaseapp.com',
    storageBucket: 'responsive-design-cac6f.firebasestorage.app',
    measurementId: 'G-P3Z5415T06',
  );

}